### ISSUE TITLE
Internal Server Error on project page

### ISSUE THREAD

**Issue by bekce** [cobyism/redmine-heroku#2]
I created and built the dyno as instructed and when I create a project and go to its url (`/projects/testprj`) I got internal server error (500) like below: 

> Internal error
> 
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> 
> If you are the Redmine administrator, check your log files for details about the error.
> 
> Back

**Comment by gastonambrogi** [comment]
Can you provide the logs when it crashes?

**Comment by fbukevin** [comment]
I face the same problem.
I use Papertrail add-on to monitor the error log.
The following is the message:

```
Sep 24 06:15:15 guarded-peak-24852 heroku/router:  at=info method=GET path="/" host=guarded-peak-24852.herokuapp.com request_id=09e91e43-239d-446f-b64c-e451d764be47 fwd="123.192.148.246" dyno=web.1 connect=0ms service=51ms status=304 bytes=700 
Sep 24 06:15:15 guarded-peak-24852 app/web.1:  Started GET "/" for 123.192.148.246 at 2016-09-24 13:15:14 +0000 
Sep 24 06:15:15 guarded-peak-24852 app/web.1:  Processing by WelcomeController#index as HTML 
Sep 24 06:15:15 guarded-peak-24852 app/web.1:    Current user: admin (id=1) 
Sep 24 06:15:15 guarded-peak-24852 app/web.1:    Rendered welcome/index.html.erb within layouts/base (7.2ms) 
Sep 24 06:15:15 guarded-peak-24852 app/web.1:  Completed 200 OK in 37.1ms (Views: 18.5ms | ActiveRecord: 10.9ms) 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    Rendered projects/show.html.erb within layouts/base (32.8ms) 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:  Completed 500 Internal Server Error in 318.9ms 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:  ActionView::Template::Error (undefined method `name' for nil:NilClass): 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      42:     <% end %> 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      43:  
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      44:     <h1><%= page_header_title %></h1> 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      45:  
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      46:     <% if display_main_menu?(@project) %> 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      47:     <div id="main-menu"> 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:      48:         <%= render_main_menu(@project) %> 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine.rb:246:in `block (2 levels) in <top (required)>' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:199:in `call' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:199:in `allowed_node?' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:166:in `block in menu_items_for' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:165:in `each' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:165:in `menu_items_for' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:90:in `render_menu' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    lib/redmine/menu_manager.rb:80:in `render_main_menu' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    app/views/layouts/base.html.erb:45:in `_app_views_layouts_base_html_erb___2716178046142617268_70231640836180' 
Sep 26 08:36:07 guarded-peak-24852 app/web.1:    app/controllers/projects_controller.rb:163:in `show' 
```
